ed25519private:
  # needed on the client if the ed25519 has a password (optional)
  password:
  # needed on the client
  path: ~/.ssh/id_ed25519

server:
  # needed on the client
  domain: localhost
  # needed on the both
  port: 8081
  # needed on the server
  authorized_keys_path: ~/.ssh/authorized_keys


keepass:
  # needed on client
  client_path: exampleFiles/exampleClient.kdbx
  # needed on server
  server_path: exampleFiles/exampleServer.kdbx
  # needed on both
  password: abcdefg12345678

ssl_certificate:
  # needed on both
  self_signed_certificate: cert.pem
  # needed on server
  key: key.pem

# if you don't want to log anything just keep the entry empty (optional)
loggingPath: log.txt